### PR TITLE
Introduce go.mod file

### PR DESCRIPTION
**Pull request by urso**

### CODE REVIEW

**Comment by andresrc** [comment]
ping @elastic/integrations-services

**Review by andrewkroh — COMMENTED** [review]
I think the `glide.yaml` could be removed as part of this. WDYT?

**Comment by urso** [comment]
Good point. Removed glide.yaml.

**Review by andrewkroh — APPROVED** [review]
LGTM. I would recommend a CI check but there is no CI for this repo.

**Comment by urso** [comment]
> LGTM. I would recommend a CI check but there is no CI for this repo.

Yeah, testing + CI will need some extra work.

**Pull request merged**
